#!/bin/busybox sh

/bin/busybox --install

mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t configfs none /sys/kernel/config
mount -t debugfs none /sys/kernel/debug
mount -t tmpfs none /tmp

exec /bin/sh -i
